version: 2
jobs:
   build:
     docker:
       - image: circleci/node:4.8
     steps:
       - checkout
       - run:
           name: Setup npm
           working_directory: ~/project/website
           command: npm install
       - run: cd website && npm run lint -- -f junit -o $CIRCLE_TEST_REPORTS/lint-results.xml
       - run: npm run test -- -R xunit --reporter-options output=$CIRCLE_TEST_REPORTS/test-results.xml

